version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_pgscada7
      POSTGRES_DB: scada_core
    volumes:
      - .postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - .postgresql/db:/var/lib/postgresql/data
    ports:
       - 5432:5432
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./postgresql/pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: always

networks:
    postgres:
      driver: bridge

volumes:
    db:
    pgadmin:

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080